# Generated by Django 5.0.7 on 2024-07-12 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_webapp', '0002_rename_courseprograms_courseprogram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseprogram',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tuition',
            name='user',
        ),
    ]
