# Generated by Django 5.0.7 on 2024-07-14 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_webapp', '0003_remove_courseprogram_user_remove_tuition_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('marks', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tuition',
            name='course_program',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.RenameField(
            model_name='courseprogram',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='courseprogram',
            name='duration',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='courseprogram',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseprogram',
            name='tuition_fee',
            field=models.IntegerField(default='15000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturerprofile',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturers', to='management_webapp.courseprogram'),
        ),
        migrations.AddField(
            model_name='lecturerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='management_webapp.courseprogram'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Tuition',
        ),
    ]
