# Generated by Django 5.0.7 on 2024-07-15 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_webapp', '0004_lecturerprofile_studentprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mother_name',
        ),
    ]
