# Generated by Django 5.0.7 on 2024-07-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_webapp', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogram',
            name='tuition_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
